#!/bin/bash
HOME="/home/dspace"

# Load current user's profile/environment
if [ -r $HOME/.profile ]; then
   echo "Loading user environment from $HOME/.profile";
   source $HOME/.profile
fi

#psql -c "update eperson set password='d2a147310ed200c73a5978baebf60e19', salt=NULL, digest_algorithm=NULL where email='dspacedemo+admin@gmail.com';"
#psql -c "update eperson set password='d2a147310ed200c73a5978baebf60e19', salt=NULL, digest_algorithm=NULL where email='dspacedemo+commadmin@gmail.com';"
#psql -c "update eperson set password='d2a147310ed200c73a5978baebf60e19', salt=NULL, digest_algorithm=NULL where email='dspacedemo+colladmin@gmail.com';"
#psql -c "update eperson set password='d2a147310ed200c73a5978baebf60e19', salt=NULL, digest_algorithm=NULL where email='dspacedemo+submit@gmail.com';"

psql -c "UPDATE eperson SET password='d2a147310ed200c73a5978baebf60e19', salt=NULL, digest_algorithm=NULL WHERE email='dspacedemo+admin@gmail.com' OR email='dspacedemo+commadmin@gmail.com' OR email='dspacedemo+colladmin@gmail.com' OR email='dspacedemo+submit@gmail.com';"
